### ISSUE TITLE
Error while authenticating

### ISSUE THREAD

**Issue by exasky** [thibauts/t411#11]
Hi !

When I try to authenticate with your node module I get this error :

```
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /var/www/node_modules/t411/index.js:197:21
    at Request.callback (/var/www/node_modules/t411/node_modules/superagent/lib/node/index.js:691:12)
    at ClientRequest.<anonymous> (/var/www/node_modules/t411/node_modules/superagent/lib/node/index.js:901:12)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
```

I think it's from the index.js class at
```var data = JSON.parse(res.text);```
res doesn't have a 'text'

**Comment by ylon** [comment]
Hi, the module is working  but the api is down right now. Don t know when
it will be fix.

**Comment by ylon** [comment]
api ok.

**Comment by exasky** [comment]
Yes sorry for the inconvenience
