### ISSUE TITLE
Node server crash when bad torrent request

### ISSUE THREAD

**Issue by exasky** [thibauts/t411#13]
Hi !

I'm here to report a bug: When doing a bad search, my node server went down.

Here's the log:

```
undefined:1
<div class="errorMessage">assert(): Assertion failed</div>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at /var/www/node_modules/t411/index.js:198:21
    at Request.callback (/var/www/node_modules/t411/node_modules/superagent/lib/node/index.js:691:12)
    at Stream.<anonymous> (/var/www/node_modules/t411/node_modules/superagent/lib/node/index.js:922:12)
    at Stream.EventEmitter.emit (events.js:117:20)
    at Unzip.<anonymous> (/var/www/node_modules/t411/node_modules/superagent/lib/node/utils.js:108:12)
    at Unzip.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

Maybe you should add a try, catch at t411/index.js line 198

Did the trick for me:

  ```
try {
      var data = JSON.parse(res.text);

      if(data.error) {
        var err = new Error(data.error);
        err.code = data.code;
        return callback(err);
      }

      callback(null, data);
    } catch (e) {
      callback("Error: " + e);
    }
```

**Comment by thibauts** [comment]
Could you open a PR with your fix using "new Error" as above ?

**Comment by ylon** [comment]
hello,
there's a pending PR for that https://github.com/thibauts/t411/pull/10

**Comment by ylon** [comment]
Sorry, forget it, the above is not good
